require("configs.virtualenv")
require("configs.plugins")
require("configs.mason")
require("configs.options")
require("configs.keymaps")
require("configs.colorscheme")
require("configs.cmp")
require("configs.telescope")
require("configs.treesitter")
require("configs.autopairs")
require("configs.comment")
require("configs.gitsigns")
require("configs.nvim-tree")
require("configs.bufferline")
require("configs.lualine")
require("configs.toggleterm")
--[[ require("user.project") ]]
require("configs.impatient")
require("configs.illuminate")
require("configs.indentline")
require("configs.alpha")
-- require("configs.lsp")
-- require("configs.dap")
require("configs.notifier")
require("configs.sessionmanager")
require("configs.scrollbar")
require("configs.colorizer")
require("configs.autocommands")
-- require("configs.jaq")
-- require("configs.neotest")
